# Generated by Django 2.2.5 on 2020-04-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reply_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
